### ISSUE TITLE
不同版本均存在SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by XueiuR** [p1r06u3/opencanary_web#40]
+ 当运行环境为python2.7时，会提示
```
Traceback (most recent call last):
  File "server.py", line 17, in <module>
    from url import url
  File "/Users/xuerui/gitrepository/opencanary_web/url.py", line 10, in <module>
    from handlers import login, hello
  File "/Users/xuerui/gitrepository/opencanary_web/handlers/login.py", line 13, in <module>
    import jwt
  File "/opt/anaconda3/envs/test2py2.7/lib/python2.7/site-packages/jwt/__init__.py", line 17, in <module>
    from .jwk import (
  File "/opt/anaconda3/envs/test2py2.7/lib/python2.7/site-packages/jwt/jwk.py", line 60
    def is_sign_key(self) -> bool:
                          ^
SyntaxError: invalid syntax
```
在网上查找，可能是和jwt版本有关？我的jwt版本是0.5.2
+ 当运行环境为python3.7时，会提示
```
Traceback (most recent call last):
  File "server.py", line 14, in <module>
    from util.task import sched, host_scheduler, check_scheduler
  File "/Users/xuerui/gitrepository/opencanary_web/util/task.py", line 12, in <module>
    from service.hostservice import hostonline
  File "/Users/xuerui/gitrepository/opencanary_web/service/hostservice.py", line 33
    print datetime.datetime.now()
                 ^
SyntaxError: invalid syntax
```
语法有问题，请问还会继续更新吗

**Comment by p1r06u3** [comment]
https://github.com/p1r06u3/opencanary_web/blob/master/requirements.txt
看一下里面用到的jwt，不是你环境中的~

**Comment by p1r06u3** [comment]
python3 目前不支持~有时间的话会支持下。好忙啊~呜呜呜

**Comment by XueiuR** [comment]
嗯嗯 看到了 已经解决 感谢
