### ISSUE TITLE
表哥，安装客户端的时候报错，帮忙看下原因

### ISSUE THREAD

**Issue by configworld768** [p1r06u3/opencanary_web#43]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-81OZ0X/simplejson/setup.py'"'"'; __file__='"'"'/tmp/pip-install-81OZ0X/simplejson/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-81OZ0X/simplejson/pip-egg-info
         cwd: /tmp/pip-install-81OZ0X/simplejson/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-81OZ0X/simplejson/setup.py", line 116, in <module>
        run_setup(not IS_PYPY)
      File "/tmp/pip-install-81OZ0X/simplejson/setup.py", line 113, in run_setup
        **kw)
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2341, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
        raise ImportError(str(exc))
    ImportError: 'module' object has no attribute 'check_specifier'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by p1r06u3** [comment]
加我微信吧： pirogue-tk
