### ISSUE TITLE
Unhandled Error Failed to load application: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object

### ISSUE THREAD

**Issue by p1r06u3** [p1r06u3/opencanary_web#46]
[root@localhost ~]# opencanaryd --start
** We hope you enjoy using OpenCanary. For more open source Canary goodness, head over to canarytokens.org. **
** The honeypot is supported by http://pirogue.org . **
[-] Failed to open opencanary.conf for reading ([Errno 2] No such file or directory: 'opencanary.conf')
[-] Using config file: /root/.opencanary.conf
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib64/python2.7/site-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib64/python2.7/site-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "/usr/bin/opencanary.tac", line 9, in <module>
    from opencanary.logger import getLogger
  File "/usr/lib/python2.7/site-packages/opencanary/logger.py", line 7, in <module>
    from twisted.internet import reactor
  File "/usr/lib64/python2.7/site-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/lib64/python2.7/site-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/usr/lib64/python2.7/site-packages/twisted/internet/default.py", line 44, in _

exceptions.TypeError: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object

Failed to load application: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object

![image](https://user-images.githubusercontent.com/17398960/74300801-ebcb8d00-4d8b-11ea-8b2e-308fde502356.png)

![image](https://user-images.githubusercontent.com/17398960/74300796-e706d900-4d8b-11ea-978c-6342bacec7b9.png)

Solved:
pip install --upgrade cffi

**Comment by p1r06u3** [comment]
Solved:
pip install --upgrade cffi
