### ISSUE TITLE
安装agent失败，登陆web无法看到agnet

### ISSUE THREAD

**Issue by bio-lin** [p1r06u3/opencanary_web#56]
[root@opencancry-web ~]# opencanaryd --start
** We hope you enjoy using OpenCanary. For more open source Canary goodness, head over to canarytokens.org. **
** The honeypot is supported by http://pirogue.org . **
[-] Failed to open opencanary.conf for reading ([Errno 2] No such file or directory: 'opencanary.conf')
[-] Using config file: /root/.opencanary.conf
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 642, in run
    runApp(config)
  File "/usr/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 376, in run
    self.application = self.createOrGetApplication()
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 441, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/lib64/python2.7/site-packages/twisted/application/app.py", line 452, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/lib64/python2.7/site-packages/twisted/application/service.py", line 405, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/lib64/python2.7/site-packages/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "/usr/bin/opencanary.tac", line 37, in <module>
    from opencanary.modules.rdp import CanaryRDP
  File "/usr/lib/python2.7/site-packages/opencanary/modules/rdp.py", line 5, in <module>
    from rdpy.protocol.rdp.rdp import RDPServerObserver
  File "/usr/lib64/python2.7/site-packages/rdpy/protocol/rdp/rdp.py", line 30, in <module>
    import tpkt, x224, sec
  File "/usr/lib64/python2.7/site-packages/rdpy/protocol/rdp/sec.py", line 25, in <module>
    import lic, tpkt
  File "/usr/lib64/python2.7/site-packages/rdpy/protocol/rdp/lic.py", line 29, in <module>
    from t125 import gcc
  File "/usr/lib64/python2.7/site-packages/rdpy/protocol/rdp/t125/gcc.py", line 27, in <module>
    import per, mcs
  File "/usr/lib64/python2.7/site-packages/rdpy/protocol/rdp/t125/mcs.py", line 34, in <module>
    import rdpy.security.rsa_wrapper as rsa
  File "/usr/lib64/python2.7/site-packages/rdpy/security/rsa_wrapper.py", line 24, in <module>
    import rsa
  File "/usr/lib/python2.7/site-packages/rsa/__init__.py", line 24, in <module>
    from rsa.key import newkeys, PrivateKey, PublicKey
exceptions.SyntaxError: Non-ASCII character '\xc3' in file /usr/lib/python2.7/site-packages/rsa/key.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details (key.py, line 1)

Failed to load application: Non-ASCII character '\xc3' in file /usr/lib/python2.7/site-packages/rsa/key.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details (key.py, line 1)

**Comment by p1r06u3** [comment]
pip uninstall rsa
