### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Tearslovefu** [p1r06u3/opencanary_web#58]
Downloading pip-20.2.1-py2.py3-none-any.whl (1.5 MB)
     |▏                               | 10 kB 4.6 kB/s eta 0:05:22ERROR: Exception:
Traceback (most recent call last):
  File "/tmp/tmp1VM5Es/pip.zip/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/tmp/tmp1VM5Es/pip.zip/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/tmp/tmp1VM5Es/pip.zip/pip/_internal/commands/install.py", line 325, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/tmp/tmp1VM5Es/pip.zip/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/tmp/tmp1VM5Es/pip.zip/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/tmp/tmp1VM5Es/pip.zip/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/tmp/tmp1VM5Es/pip.zip/pip/_internal/operations/prepare.py", line 469, in prepare_linked_requirement
    hashes=self._get_linked_req_hashes(req)
  File "/tmp/tmp1VM5Es/pip.zip/pip/_internal/operations/prepare.py", line 259, in unpack_url
    hashes=hashes,
  File "/tmp/tmp1VM5Es/pip.zip/pip/_internal/operations/prepare.py", line 130, in get_http_url
    link, downloader, temp_dir.path, hashes
  File "/tmp/tmp1VM5Es/pip.zip/pip/_internal/operations/prepare.py", line 282, in _download_http_url
    for chunk in download.chunks:
  File "/tmp/tmp1VM5Es/pip.zip/pip/_internal/cli/progress_bars.py", line 168, in iter
    for x in it:
  File "/tmp/tmp1VM5Es/pip.zip/pip/_internal/network/utils.py", line 88, in response_chunks
    decode_content=False,
  File "/tmp/tmp1VM5Es/pip.zip/pip/_vendor/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/tmp/tmp1VM5Es/pip.zip/pip/_vendor/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/tmp1VM5Es/pip.zip/pip/_vendor/urllib3/response.py", line 451, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
/usr/bin/python: No module named pip
################pip is installed############
############正在同步最新版本opencanary_web,并且安装第三方依赖包##########
Cloning into '/usr/local/src/opencanary_web'...
remote: Enumerating objects: 144, done.
remote: Counting objects: 100% (144/144), done.
remote: Compressing objects: 100% (110/110), done.
Receiving objects:  13% (163/1247), 44.01 KiB | 1024 bytes/s

**Comment by p1r06u3** [comment]
/usr/bin/python: No module named pip
机器上还没有pip，可能是因为网速的原因，建议通过手工安装方式进行安装。
